# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cnn_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63nn_controller.proto\x12\x0e\x63nn_controller\"I\n\x11PredictionRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x11\n\timg_width\x18\x02 \x01(\x05\x12\x12\n\nimg_height\x18\x03 \x01(\x05\"2\n\x12PredictionResponse\x12\r\n\x05\x63lass\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\x05\x32\x62\n\tPredictor\x12U\n\nPrediction\x12!.cnn_controller.PredictionRequest\x1a\".cnn_controller.PredictionResponse\"\x00\x42\x1b\x42\x0e\x43NN_ControllerP\x01\xa2\x02\x06\x43NNCTRb\x06proto3')



_PREDICTIONREQUEST = DESCRIPTOR.message_types_by_name['PredictionRequest']
_PREDICTIONRESPONSE = DESCRIPTOR.message_types_by_name['PredictionResponse']
PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONREQUEST,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.PredictionRequest)
  })
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESPONSE,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.PredictionResponse)
  })
_sym_db.RegisterMessage(PredictionResponse)

_PREDICTOR = DESCRIPTOR.services_by_name['Predictor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\016CNN_ControllerP\001\242\002\006CNNCTR'
  _PREDICTIONREQUEST._serialized_start=40
  _PREDICTIONREQUEST._serialized_end=113
  _PREDICTIONRESPONSE._serialized_start=115
  _PREDICTIONRESPONSE._serialized_end=165
  _PREDICTOR._serialized_start=167
  _PREDICTOR._serialized_end=265
# @@protoc_insertion_point(module_scope)
