# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cnn_controller_pb2 as cnn__controller__pb2


class PredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prediction = channel.unary_unary(
                '/cnn_controller.Predictor/Prediction',
                request_serializer=cnn__controller__pb2.PredictionRequest.SerializeToString,
                response_deserializer=cnn__controller__pb2.PredictionResponse.FromString,
                )
        self.Initialization = channel.unary_unary(
                '/cnn_controller.Predictor/Initialization',
                request_serializer=cnn__controller__pb2.InitRequest.SerializeToString,
                response_deserializer=cnn__controller__pb2.InitResponse.FromString,
                )


class PredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prediction(self, request, context):
        """Sends a prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialization(self, request, context):
        """initializes the CNN with the given parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prediction': grpc.unary_unary_rpc_method_handler(
                    servicer.Prediction,
                    request_deserializer=cnn__controller__pb2.PredictionRequest.FromString,
                    response_serializer=cnn__controller__pb2.PredictionResponse.SerializeToString,
            ),
            'Initialization': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialization,
                    request_deserializer=cnn__controller__pb2.InitRequest.FromString,
                    response_serializer=cnn__controller__pb2.InitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cnn_controller.Predictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Predictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cnn_controller.Predictor/Prediction',
            cnn__controller__pb2.PredictionRequest.SerializeToString,
            cnn__controller__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Initialization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cnn_controller.Predictor/Initialization',
            cnn__controller__pb2.InitRequest.SerializeToString,
            cnn__controller__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class OutputCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreOutput = channel.unary_unary(
                '/cnn_controller.OutputCollector/StoreOutput',
                request_serializer=cnn__controller__pb2.OutputStorageRequest.SerializeToString,
                response_deserializer=cnn__controller__pb2.OutputSotrageResponse.FromString,
                )


class OutputCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreOutput(self, request, context):
        """Send output from computational node to storage node (typically not the sender node)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OutputCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreOutput,
                    request_deserializer=cnn__controller__pb2.OutputStorageRequest.FromString,
                    response_serializer=cnn__controller__pb2.OutputSotrageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cnn_controller.OutputCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OutputCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cnn_controller.OutputCollector/StoreOutput',
            cnn__controller__pb2.OutputStorageRequest.SerializeToString,
            cnn__controller__pb2.OutputSotrageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
