# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cnn_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63nn_controller.proto\x12\x0e\x63nn_controller\"2\n\x14OutputStorageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"C\n\x15OutputSotrageResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"I\n\x11PredictionRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x11\n\timg_width\x18\x02 \x01(\x05\x12\x12\n\nimg_height\x18\x03 \x01(\x05\"K\n\x12PredictionResponse\x12\x12\n\ndata_class\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\x05\x12\x12\n\nerror_code\x18\x03 \x01(\x05\"Z\n\x0bInitRequest\x12\x14\n\x0csample_limit\x18\x01 \x01(\x05\x12\x0e\n\x06\x65pochs\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\x12\n\nimg_height\x18\x04 \x01(\x05\"%\n\x0cInitResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x32\xb1\x01\n\tPredictor\x12U\n\nPrediction\x12!.cnn_controller.PredictionRequest\x1a\".cnn_controller.PredictionResponse\"\x00\x12M\n\x0eInitialization\x12\x1b.cnn_controller.InitRequest\x1a\x1c.cnn_controller.InitResponse\"\x00\x32o\n\x0fOutputCollector\x12\\\n\x0bStoreOutput\x12$.cnn_controller.OutputStorageRequest\x1a%.cnn_controller.OutputSotrageResponse\"\x00\x42\x1b\x42\x0e\x43NN_ControllerP\x01\xa2\x02\x06\x43NNCTRb\x06proto3')



_OUTPUTSTORAGEREQUEST = DESCRIPTOR.message_types_by_name['OutputStorageRequest']
_OUTPUTSOTRAGERESPONSE = DESCRIPTOR.message_types_by_name['OutputSotrageResponse']
_PREDICTIONREQUEST = DESCRIPTOR.message_types_by_name['PredictionRequest']
_PREDICTIONRESPONSE = DESCRIPTOR.message_types_by_name['PredictionResponse']
_INITREQUEST = DESCRIPTOR.message_types_by_name['InitRequest']
_INITRESPONSE = DESCRIPTOR.message_types_by_name['InitResponse']
OutputStorageRequest = _reflection.GeneratedProtocolMessageType('OutputStorageRequest', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTSTORAGEREQUEST,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.OutputStorageRequest)
  })
_sym_db.RegisterMessage(OutputStorageRequest)

OutputSotrageResponse = _reflection.GeneratedProtocolMessageType('OutputSotrageResponse', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTSOTRAGERESPONSE,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.OutputSotrageResponse)
  })
_sym_db.RegisterMessage(OutputSotrageResponse)

PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONREQUEST,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.PredictionRequest)
  })
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESPONSE,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.PredictionResponse)
  })
_sym_db.RegisterMessage(PredictionResponse)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), {
  'DESCRIPTOR' : _INITRESPONSE,
  '__module__' : 'cnn_controller_pb2'
  # @@protoc_insertion_point(class_scope:cnn_controller.InitResponse)
  })
_sym_db.RegisterMessage(InitResponse)

_PREDICTOR = DESCRIPTOR.services_by_name['Predictor']
_OUTPUTCOLLECTOR = DESCRIPTOR.services_by_name['OutputCollector']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\016CNN_ControllerP\001\242\002\006CNNCTR'
  _OUTPUTSTORAGEREQUEST._serialized_start=40
  _OUTPUTSTORAGEREQUEST._serialized_end=90
  _OUTPUTSOTRAGERESPONSE._serialized_start=92
  _OUTPUTSOTRAGERESPONSE._serialized_end=159
  _PREDICTIONREQUEST._serialized_start=161
  _PREDICTIONREQUEST._serialized_end=234
  _PREDICTIONRESPONSE._serialized_start=236
  _PREDICTIONRESPONSE._serialized_end=311
  _INITREQUEST._serialized_start=313
  _INITREQUEST._serialized_end=403
  _INITRESPONSE._serialized_start=405
  _INITRESPONSE._serialized_end=442
  _PREDICTOR._serialized_start=445
  _PREDICTOR._serialized_end=622
  _OUTPUTCOLLECTOR._serialized_start=624
  _OUTPUTCOLLECTOR._serialized_end=735
# @@protoc_insertion_point(module_scope)
